# Generated by Django 4.1.2 on 2022-10-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_comment_created_at_comment_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
