# Generated by Django 4.1.2 on 2022-10-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_like_post_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
